service: image-processor

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-webpack

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

functions:
  getImages:
    handler: handler.getImages

    events:
      - http:
          path: getImages
          method: get